
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ElementalBackHero
{
public sealed partial class RuneData : Luban.BeanBase
{
    public RuneData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        DisplayName = _buf.ReadString();
        ElementType = (ElementType)_buf.ReadInt();
        RuneKindType = (RuneKindType)_buf.ReadInt();
        RarityType = (RarityType)_buf.ReadInt();
        DrawEffectGroupId = _buf.ReadInt();
        ResonanceExperience = _buf.ReadInt();
        UnstableValue = _buf.ReadInt();
        IsUnstable = _buf.ReadBool();
        ExistenceScopeType = (RuneExistenceScopeType)_buf.ReadInt();
        RemovalTimingType = (RuneRemovalTimingType)_buf.ReadInt();
        RewardEligible = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Tags.Add(_e0);}}
        Description = _buf.ReadString();
        ContentScopeType = (ContentScopeType)_buf.ReadInt();
    }

    public static RuneData DeserializeRuneData(ByteBuf _buf)
    {
        return new RuneData(_buf);
    }

    /// <summary>
    /// 고정 콘텐츠 ID. 사용 범위: 10001~19999.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 고정 심볼 키.
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 표시 이름.
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 주 원소.
    /// </summary>
    public readonly ElementType ElementType;
    /// <summary>
    /// 기능 분류.
    /// </summary>
    public readonly RuneKindType RuneKindType;
    /// <summary>
    /// 희귀도.
    /// </summary>
    public readonly RarityType RarityType;
    /// <summary>
    /// 드로우 시 실행할 EffectGroupData ID. 0은 효과 없음.
    /// </summary>
    public readonly int DrawEffectGroupId;
    /// <summary>
    /// 보상 룬을 공명 재료로 사용할 때 제공하는 경험치.
    /// </summary>
    public readonly int ResonanceExperience;
    /// <summary>
    /// 드로우 시 증가하는 혼돈과 가방 혼돈 총량.
    /// </summary>
    public readonly int UnstableValue;
    /// <summary>
    /// 혼돈/오염 전용 룬 판별. 일반 룬의 unstable_value와 별도.
    /// </summary>
    public readonly bool IsUnstable;
    /// <summary>
    /// Run persistent 또는 current Battle only.
    /// </summary>
    public readonly RuneExistenceScopeType ExistenceScopeType;
    /// <summary>
    /// 제거 시점.
    /// </summary>
    public readonly RuneRemovalTimingType RemovalTimingType;
    /// <summary>
    /// 일반 보상 후보 허용 여부.
    /// </summary>
    public readonly bool RewardEligible;
    /// <summary>
    /// 검색과 규칙 태그.
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// 룬 역할과 lifecycle.
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// Act 1 Complete Demo release-scope classification.
    /// </summary>
    public readonly ContentScopeType ContentScopeType;
   
    public const int __ID__ = 884879908;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "displayName:" + DisplayName + ","
        + "elementType:" + ElementType + ","
        + "runeKindType:" + RuneKindType + ","
        + "rarityType:" + RarityType + ","
        + "drawEffectGroupId:" + DrawEffectGroupId + ","
        + "resonanceExperience:" + ResonanceExperience + ","
        + "unstableValue:" + UnstableValue + ","
        + "isUnstable:" + IsUnstable + ","
        + "existenceScopeType:" + ExistenceScopeType + ","
        + "removalTimingType:" + RemovalTimingType + ","
        + "rewardEligible:" + RewardEligible + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "description:" + Description + ","
        + "contentScopeType:" + ContentScopeType + ","
        + "}";
    }
}
}

